name: Create production promotion pull request
on:
  push:
    branches:
      - develop
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        #   ref: main
      # - name: Reset promotion branch
      #   run: |
      #     git fetch origin main:main
      #     git reset --hard main
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: main
          token: ${{ secrets.PAT_PR }}
          assignees: Ajaynano
          labels: |
            report
            automated pr
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"   